services:
  mysql:
    image: mysql:8.0.36-debian
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    networks:
      - hungnetwork
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    networks:
      - hungnetwork
networks:
  hungnetwork:

# docker-compose -f ./docker-compose.yml down
# docker-compose -f ./docker-compose.yml up -d