server:
  port: 8888

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/manager_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
