jwt:
  signerkey: "dDrAdtWaqgCiilX7V4z7uxZ6rU7vlbaTgj02FUswCkegR6H1TANcd5LipojaqhKN"
  valid-duration: 3600
  refreshable-duration: 36000

server:
  port: 8888

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/manager_service"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    email: mailtestservice.122@gmail.com
    password: nisdeiphottbqdlj
    protocol: smtp
    isSSL: false

  elasticsearch:
    rest:
      uris: "http://localhost:9200"