jwt:
  signerkey: "dDrAdtWaqgCiilX7V4z7uxZ6rU7vlbaTgj02FUswCkegR6H1TANcd5LipojaqhKN"
  valid-duration: 60
  refreshable-duration: 120

server:
  port: 8888

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/manager_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
